export const terms = {
  title: 'Terms of Service',
  lastUpdated: 'Last updated: August 23, 2025',
  educationalNotice: {
    title: '⚠️ IMPORTANT NOTICE: Educational Platform',
    description: 'This website is an educational platform designed exclusively for QA testing training and practice.',
    warnings: [
      'DO NOT enter real personal information or sensitive data',
      'All data should be used for testing purposes only',
      'Temporary password feature is for learning convenience and should never be used in production',
      'Data stored on this platform may be deleted at any time',
    ],
  },
  section1: {
    title: '1. Acceptance of Terms and Service Purpose',
    description: 'By accessing or using QA Learning 101, you agree to these Terms and understand that this platform is provided for educational purposes only.',
    additionalInfo: 'This platform is designed for QA engineers, testers, and developers to practice various testing scenarios. It is not a production service and should only be used for learning purposes.',
  },
  section2: {
    title: '2. Special Terms for Temporary Password Feature',
    description: 'This platform provides a temporary password feature for educational convenience. This is designed solely for educational purposes and must never be used in production services.',
    tempPasswordWarnings: [
      'Temporary passwords are displayed directly on screen and are not sent via email',
      'This is an educational feature to allow testing without a real email system',
      'Anyone can receive a temporary password with just an email address, so DO NOT use real email or personal information',
      'Generated temporary passwords expire after 30 minutes',
      'This feature is an intentional vulnerability for security testing education',
    ],
    restrictions: 'The following actions are prohibited:',
    restrictionsList: [
      'Using real personal email addresses',
      'Entering real personal information or sensitive data',
      'Creating accounts with real information of others',
      'Using the service for purposes other than learning',
      'Disrupting or abusing the service',
    ],
  },
  section3: {
    title: '3. Data and Content Management',
    description: 'Due to the educational nature of this platform, all data is temporary and used for learning purposes only.',
    dataPolicy: [
      'All user data is considered test data',
      'Data may be reset periodically',
      'No backup or data recovery services are provided',
      'Do not store real content or important information',
    ],
  },
  section4: {
    title: '4. Prohibited Activities',
    description: 'The following activities are strictly prohibited:',
    prohibitedList: [
      'Harassment or abuse of other users',
      'Spamming or unauthorized advertising',
      'Reverse engineering the service',
      'Creating multiple accounts to evade restrictions',
    ],
  },
  section5: {
    title: '5. Intellectual Property and Educational Materials',
    description: 'This platform is an open-source educational project.',
    rights: [
      'Platform source code is freely available for educational purposes',
      'QA test scenarios and learning materials are shared with the community',
      'Test data generated by users may be shared for educational purposes',
    ],
  },
  section6: {
    title: '6. Disclaimer',
    description: 'As an educational platform, we clearly state:',
    disclaimers: [
      'This service is provided for educational purposes only and does not offer production-level security',
      'Intentional test vulnerabilities may be included',
      'Data security and privacy are not guaranteed',
      'Service availability and data persistence are not guaranteed',
      'Behavior may differ from real production environments',
    ],
  },
  section7: {
    title: '7. Limitation of Liability',
    description: 'QA Learning 101 is not liable for:',
    limitations: [
      'Any damages resulting from use outside educational purposes',
      'Information leaks due to entering real personal information',
      'Data loss or service interruption',
      'Issues arising from misuse of the temporary password feature',
      'Impact from bugs or vulnerabilities discovered during testing',
    ],
  },
  section8: {
    title: '8. Termination',
    description: 'We may terminate or suspend your account immediately, without prior notice or liability, for any reason.',
  },
  section9: {
    title: '9. Privacy and Security Guidelines',
    description: 'Users must follow these security guidelines:',
    securityGuidelines: [
      'Never use real passwords',
      'Never enter real credit card information',
      'Never enter real social security numbers or ID information',
      'Never use email/password combinations from other services',
      'Always use fake test data for all inputs',
    ],
  },
  section10: {
    title: '10. Changes to Terms',
    description: 'Terms may be updated frequently to improve the educational platform.',
  },
  section11: {
    title: '11. Contact Information',
    description: 'For questions about these Terms of Service, please contact us at:',
    email: 'support@qalearningweb.com',
    note: 'We welcome feedback and suggestions for improving this educational platform.',
  },
};