nodeLinker: node-modules

# Network timeout 설정 (밀리초)
httpTimeout: 300000
httpRetry: 10

# 캐시 설정
enableGlobalCache: true
enableMirror: false

# 네트워크 동시성 설정
networkConcurrency: 8

# 압축 설정
compressionLevel: 0